In [1]:
import numpy as np

In [2]:
def normal(shape):
    N_M = shape[1]
    return np.random.normal(0, 1 / np.sqrt(N_M), size=shape)

def uniform(shape):
    N_M = shape[1]
    return np.random.uniform(-1 / np.sqrt(N_M), 1 / np.sqrt(N_M), size=shape)


In [8]:
n = 128
m = 64
k = 1

yS = 3

x = np.zeros(n)
z = np.zeros(m)

C = normal((n**2, n**2))
D = normal((n**2, m))

F = normal((m, m))
H = normal((m, n**2))

W = np.zeros((n, n))


I = np.array([1])

W_in_1 = uniform((n, k))
W_in_2 = uniform((m, k))
W_out = uniform((yS, n))

b_out = np.array([1, 1, 1])




In [4]:
def phi(x):
    return np.tanh(x)

def Phi(x):
    return np.outer(np.tanh(x), np.tanh(x).T).flatten()

def psi(z):
    return 1 / (1 + np.exp(-z))

In [24]:
def Softmax(y):
    exp_y = np.exp(y)
    return exp_y / np.sum(exp_y)

In [25]:
tau = 0.01
gamma = 0.1
T = int(10)

for t in range(T):
    x = (1 - gamma) * x + gamma * W @ phi(x) + W_in_1 @ I
    W = (1 - gamma) * W + gamma * ( C @ Phi(x) + D @ psi(z)).reshape(n, n)
    z = (1 - gamma * tau) * z + gamma * tau * (F @ psi(z) + H @ Phi(x) + W_in_2 @ I)
    y = W_out @ x + b_out

    print(Softmax(y))

#print(y)




[9.12978042e-01 8.61554679e-02 8.66490196e-04]
[0.89440398 0.10441328 0.00118275]
[0.88041383 0.11801499 0.00157117]
[0.8858789 0.1120748 0.0020463]
[0.91897752 0.0786582  0.00236429]
[0.94767233 0.04971187 0.0026158 ]
[0.9658205  0.03134299 0.00283651]
[0.9748353  0.02201563 0.00314907]
[0.97698632 0.01925529 0.00375839]
[0.97623689 0.01908899 0.00467412]


__todo - backpropagation__